env: DEV

application:
  groupId: "@project.groupId@"
  artifactId: "@project.artifactId@"
  version: "@project.version@"
  commitId: "@commitId@"
  commitDate: "@commitDate@"
  name: "demo"
  wiki: "https://inugami.io/mock/error/{0}/{1}"
  instanceName: "inu"
  instanceNumber: "001"
inugami:
  monitoring:
    interceptors:
      kpi:
        enabled: true
    internal:
      interval: 10000
    iolog:
      enabled: false
    interceptor:
      url:
        skip: .*api-docs.*;.*swagger-ui.*
    exception:
      show:
        detail:
          enabled: true
jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
spring:
  datasource:
    url: jdbc:h2:mem:inugami_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

springdoc:
  api-docs:
    path: /api-docs


