version: "3"
services:

  elastic:
    image: sebp/elk:8.6.1
    ports:
      - "5601:5601"
      - "9200:9200"
    expose:
      - 5601
      - 9200

    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - inugami

networks:
  inugami:
    driver: bridge
